### ISSUE TITLE
Unexpected contents for wxPython archive

### ISSUE THREAD

**Issue by mattdreezer** [smsearcy/zeal-feeds#7]
Zeal-feeds fails to install the wxPython docset as it is failing the test that is looking for the `.docset` string at the end of `docset_folder.name`.  The folder name for the wxPython docset is `wxPython-4.0.7.docset`.  Suggest that line 67 in zeal.py is modified to the following:

`if not (docset_folder and docset_folder.name.endswith(".docset")):`

**Comment by smsearcy** [comment]
Thank you for reporting this, I think you're right about the proposed fix.  You're welcome to submit a PR or I should be able to get this fixed shortly.

*Edit: Actually, there's a little more to the fix because it created a folder with the version number in the name.  I'll work on getting this fixed.*

**Comment by smsearcy** [comment]
I have a working implementation but I'm having some trouble getting the updated package to PyPI.  I'll let you know once I get that worked out.

**Comment by smsearcy** [comment]
Verion 0.2.3 has been pushed to PyPI to address this issue.

Thank you again for reporting it!
